#!/usr/bin/env bash
# Infinite loop printing message; prints "I am invincible!!!" on SIGTERM instead of terminating

trap 'echo "I am invincible!!!"' SIGTERM

while true; do
  echo "To infinity and beyond"
  sleep 2
done
